### ISSUE TITLE
Нет traceId в логах

### ISSUE THREAD

**Issue by nmorgunov** [Byndyusoft/node-pino-logger-factory#5]
В логах нет traceId

Пример лога:
```
{
  "level": "error",
  "time": "2021-06-21T11:55:05.967Z",
  "pid": 17,
  "hostname": "worktime-calculator-746977c695-rrhx8",
  "name": "lmru-bpms-ved--worktime-calculator",
  "version": "1.0.3",
  "req": {
    "id": 3,
    "method": "GET",
    "url": "/worktimeCalculator/spentTime?startDate=2021-05-05&endDate=2021-05-06&organizationId=60745b429f98c50018295147",
    "query": { "startDate": "2021-05-05", "endDate": "2021-05-06", "organizationId": "60745b429f98c50018295147" },
    "params": { "0": "worktimeCalculator/spentTime" },
    "headers": {
    ///
    },
    "remoteAddress": "...",
    "remotePort": ....
  },
  "error": {
    "name": "RangeError",
    "message": "Invalid time zone specified: France / Paris",
    "stack": "RangeError: Invalid time zone specified: France / Paris\n    at Date.toLocaleString (<anonymous>)\n    at M.f.tz (/app/node_modules/dayjs/plugin/timezone.js:1:1035)\n    at WorktimeCalculatorService.calculateSpentTime (/app/src/worktimeCalculator/worktimeCalculator.service.ts:87:46)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at /app/node_modules/@nestjs/core/router/router-proxy.js:9:17"
  },
  "msgTemplateHash": "5b5b3bf3",
  "msg": "Invalid time zone specified: France / Paris"
}
```

Конфигурирование логгера
![image](https://user-images.githubusercontent.com/46551804/122759985-0aad2e00-d2b4-11eb-9c61-ff430b812ab3.png)

использование логгера
```  
this._logger.error({ error: exception }, exception.message);
```

**Comment by KillWolfVlad** [comment]
In [nest-template](https://github.com/Byndyusoft/nest-template) `traceId` in logs exists.
